### PR TITLE
check for /etc/default/minio is not empty

### PR DESCRIPTION
**Pull request by mkahric**
Add assertion check is default environment file exist and not empty.
Add optional assertion check is MINIO_VOLUMES set (can be used from Systemd 246/247 instead of ExecStartPre Bash one-liner).

### CODE REVIEW

**Comment by justinclift** [comment]
Don't suppose it's possible to add an assertion which checks if the given [user/group combo](https://github.com/minio/minio-service/blob/e36ff7d514025705530b15ccae6447995a65c293/linux-systemd/minio.service#L11-L12) for the service actually exists?

Asking out of idle curiosity more than anything, as that specific thing has caught me out a few times.  eg "minio" user instead of "minio-user", and forgetting to update the .service file :wink:

**Comment by mkahric** [comment]
From systemd.unit manual:

> ConditionUser= takes a numeric "UID", a UNIX user name, or the special value "@system". This condition may be used to check whether the service manager is running as the given user. The special value "@system" can be used to check if the user id is within the system user range. This option is not useful for system services, as the system manager exclusively runs as the root user, and thus the test result is constant.

So, this is not what you need.

**Comment by justinclift** [comment]
No worries @mkahric, it was just a thought. :smile:

**Comment by mkahric** [comment]
Maybe you can try with this bash one-liner:
`MINIOUSER=$(grep -i ^user= /etc/systemd/system/minio.service | cut -d= -f2); [[ $(id -nu $MINIOUSER) ]] || echo "User $MINIOUSER is not set!" && systemctl start minio.service`

**Review by harshavardhana — APPROVED** [review]

**Pull request merged**
